import clsx from "clsx";
import { dir } from "i18next";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { Footer } from "~/components/Footer";
import { Header } from "~/components/Header";
import { Providers } from "~/components/Providers";
import { useTranslation as getTranslation } from "~/i18n";
import { poppins } from "~/public/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  const { i18n } = await getTranslation();

  return (
    <html lang={i18n.resolvedLanguage} dir={dir(i18n.resolvedLanguage)}>
      <body
        className={clsx(
          "relative flex flex-col",
          poppins.className,
          poppins.variable
        )}
      >
        <Providers>
          <Header />
          {/* <main className="flex flex-col min-h-screen">{children}</main> */}
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
